const $=id=>document.getElementById(id);let products=[],categories=[],photo=null,taxas=JSON.parse(localStorage.getItem("taxasEntrega")||"[]");
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(b.dataset.s).classList.add("active");document.querySelectorAll("[data-s]").forEach(x=>x.classList.remove("active"));b.classList.add("active")});$("novoProduto").onclick=()=>{$("formProduto").classList.remove("hidden")};$("cancelarProduto").onclick=()=>{$("formProduto").classList.add("hidden")};$("salvarProduto").onclick=saveProduct;$("fotoProduto").onchange=e=>{let f=e.target.files[0],r=new FileReader();if(f){r.onload=()=>photo=r.result;r.readAsDataURL(f)}};$("novaCategoria").onclick=()=>{$("formCategoria").classList.remove("hidden")};$("cancelarCategoria").onclick=()=>{$("formCategoria").classList.add("hidden")};$("salvarCategoria").onclick=saveCategory;$("modoEntrega").onchange=()=>{$("nomeTaxa").textContent=$("modoEntrega").value==="bairro"?"Bairro":"Até quantos km?"};$("addTaxa").onclick=addTaxa;loadCategories();loadProducts();renderTaxas()});
async function loadCategories(){let {data,error}=await supabaseClient.from("categorias").select("*").order("nome");if(error){$("listaCategorias").innerHTML="Erro: "+error.message;return}categories=data||[];$("categoriaProduto").innerHTML=categories.filter(c=>c.ativo!==false).map(c=>`<option value="${c.nome}">${c.nome}</option>`).join("")||"<option>Pastéis</option>";$("listaCategorias").innerHTML=categories.map(c=>`<div class="item"><b>${c.nome}</b><p>${c.descricao||""}</p><div class="actions"><button class="btn danger" onclick="deleteCategory(${c.id})">Excluir</button></div></div>`).join("")||"Nenhuma categoria."}
async function saveCategory(){let nome=$("nomeCategoria").value.trim();if(!nome)return alert("Digite o nome.");let p={nome,descricao:$("descricaoCategoria").value.trim(),ativo:$("categoriaAtiva").checked};let {error}=await supabaseClient.from("categorias").insert(p);if(error)return alert(error.message);$("formCategoria").classList.add("hidden");loadCategories()}
window.deleteCategory=async id=>{if(!confirm("Excluir categoria?"))return;let {error}=await supabaseClient.from("categorias").delete().eq("id",id);if(error)alert(error.message);else loadCategories()}
async function loadProducts(){let {data,error}=await supabaseClient.from("produtos").select("*").order("id",{ascending:false});if(error){$("listaProdutos").innerHTML="Erro: "+error.message;return}products=data||[];$("listaProdutos").innerHTML=products.map(p=>`<div class="item"><b>${p.nome}</b><p>${p.categoria||""}</p><p>R$ ${Number(p.preco).toFixed(2).replace(".",",")}</p><div class="actions"><button class="btn danger" onclick="deleteProduct(${p.id})">Excluir</button></div></div>`).join("")||"Nenhum produto."}
async function saveProduct(){let nome=$("nomeProduto").value.trim(),preco=Number($("precoProduto").value);if(!nome||!preco)return alert("Preencha nome e preço.");let p={nome,preco,categoria:$("categoriaProduto").value,descricao:$("descricaoProduto").value.trim(),ativo:$("produtoAtivo").checked};if(photo)p.foto=photo;let {error}=await supabaseClient.from("produtos").insert(p);if(error)return alert("Erro: "+error.message);$("formProduto").classList.add("hidden");$("nomeProduto").value="";$("precoProduto").value="";$("descricaoProduto").value="";photo=null;loadProducts()}
window.deleteProduct=async id=>{if(!confirm("Excluir produto?"))return;let {error}=await supabaseClient.from("produtos").delete().eq("id",id);if(error)alert(error.message);else loadProducts()}
function addTaxa(){let nome=$("valorArea").value.trim(),taxa=Number($("valorTaxa").value);if(!nome)return alert("Preencha a área.");taxas.push({id:Date.now(),nome,taxa});localStorage.setItem("taxasEntrega",JSON.stringify(taxas));renderTaxas()}
function renderTaxas(){$("listaTaxas").innerHTML=taxas.map(t=>`<div class="item">${t.nome} — R$ ${Number(t.taxa).toFixed(2).replace(".",",")}</div>`).join("")}